#!/usr/bin/zsh

tmp="$(mktemp)"
ranger --choosedir="$tmp" "$@"
if [ -f "$tmp" ]; then
	dir="$(cat "$tmp")"
	rm -f "$tmp"
	if [ -d "$dir" ]; then
		if [ "$dir" != "$(pwd)" ]; then
			cd "$dir"
		fi
	fi
fi
zsh